### ISSUE TITLE
Add gRPC API support

### ISSUE THREAD

**Issue by pdt256** [inklabs/rangedb#2]
As a RangeDB client, I want to retrieve events via gRPC using protocol buffers; so that my services can efficiently process events.

**Implementation Details:**

Mirror the same functionality as the HTTP API examples here:
https://github.com/inklabs/rangedb/tree/master/examples

**Todo**

- [x] Get All Events
- [x] Get Events by Aggregate Type(s)
- [x] Get Events by Stream
- [x] Save Events
- [x] Stream All Events
- [x] Stream Events by Aggregate Type(s)

**Comment by pdt256** [comment]
Released in [v0.3.0](https://github.com/inklabs/rangedb/releases/tag/v0.3.0)
